### ISSUE TITLE
대출 매뉴의 뒤로가기 키 추가

### ISSUE THREAD

**Issue by KyungjeCho** [dldkddkd/Stock-II-new#11]
메뉴에서 2.대출을 누르고 뒤로가기 키가 없다.

**Comment by KyungjeCho** [comment]
2. 대출에서 w, s 키를 입력하여 0 ~ 한도 금액 조정하여 대출하는 것으로 바꾸는 것은 어떤가요? 이렇게하면 문자를 입력하여 쓰레기 값을 피할 수 있고 뒤로가기 키도 구현할 수 있습니다

**Comment by dldkddkd** [comment]
대출 메뉴에서

**Comment by dldkddkd** [comment]
뒤로가기 키는 없지만 뒤로가기는 구현되어 있으므로 일단은 이슈에서 내리겠습니다
