### ISSUE TITLE
시작할때 1,2,3 키 이외의 키를 입력할 경우 

### ISSUE THREAD

**Issue by KyungjeCho** [dldkddkd/Stock-II-new#15]
1, 2, 3 이외의 알파벳을 입력하면 주식을 살 수가 없습니다

**Comment by KyungjeCho** [comment]
주식을 살 때, 문자열을 입력하면 다시 살 수 없습니다

**Comment by dldkddkd** [comment]
이제 시작할 때 1,2,3 키 이외의 키를 입력해도 게임이 정상적으로 진행됩니다
