### ISSUE TITLE
시간 흐름 모드

### ISSUE THREAD

**Issue by KyungjeCho** [dldkddkd/Stock-II-new#7]
시간의 흐름방식을 선택했을 때, 키보드 하나하나 누를 때마다 시간이 지나가서 원하는 정보를 얻기 힘들고 원하는 주식을 그 타이밍에 구매하거나 팔기가 어렵다

**Comment by dldkddkd** [comment]
이제 시간의 흐름방식을 선택했을 때 주식의 가격이 변동되지 않습니다
